### ISSUE TITLE
elasticsearch indexing timeout on first boot

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/liquidinvestigations#140]
I'm getting this error when running first boot on cloud-x86:

```
+ /opt/hoover/bin/hoover search update testdata
       Traceback (most recent call last):
         File "/opt/hoover/search/manage.py", line 10, in <module>
           execute_from_command_line(sys.argv)
         File "/opt/hoover/venvs/search/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
           utility.execute()
         File "/opt/hoover/venvs/search/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
         File "/opt/hoover/venvs/search/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
           self.execute(*args, **cmd_options)
         File "/opt/hoover/venvs/search/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
           output = self.handle(*args, **options)
         File "/opt/hoover/search/hoover/search/management/commands/update.py", line 22, in handle
           report = update_collection(Collection.objects.get(name=collection))
         File "/opt/hoover/search/hoover/search/index.py", line 71, in update_collection
           es.bulk_index(collection.id, docs)
         File "/opt/hoover/search/hoover/search/es.py", line 66, in bulk_index
           request_timeout=60,
         File "/opt/hoover/venvs/search/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 194, in bulk
           for ok, item in streaming_bulk(client, actions, **kwargs):
         File "/opt/hoover/venvs/search/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
           for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
         File "/opt/hoover/venvs/search/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 134, in _process_bulk_chunk
           raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
       elasticsearch.helpers.BulkIndexError: ('1 document(s) failed to index.', [{'index': {'_type': 'doc', 'error': {'type': 'timeout_exception', 'reason': 'Failed to acknowledge mapping update within [30s]'}, '_index': 'testdata', 'status': 500, '_id': '226'}}])
```

**Comment by gabriel-v** [comment]
not reproduced in recent builds, see to it later

**Comment by gabriel-v** [comment]
never happened again, closing
